controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint_lift
      - joint_wrist_yaw
      - joint_wrist_pitch
      - joint_wrist_roll
      - joint_gripper_slide
      - joint_head_pan
      - joint_head_tilt

    command_interfaces:
      - position
      # - velocity
      # - effort

    state_interfaces:
      - position
      - velocity

    open_loop_control: True