version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
    - cmake

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
