controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

upper_body_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - head_1_joint
      - head_2_joint
      - torso_lift_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

upper_body_velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - torso_lift_joint
      - head_1_joint
      - head_2_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

arm_left_position_controller: 
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint

arm_right_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

torso_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - torso_lift_joint

head_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - head_1_joint
      - head_2_joint

arm_left_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
    command_interfaces:
      - position
      # - velocity
      # - effort
    state_interfaces:
      - position
      - velocity
    open_loop_control: True

arm_right_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint   
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
    command_interfaces:
      - position
      # - velocity
      # - effort
    state_interfaces:
      - position
      - velocity
    open_loop_control: True

torso_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - torso_lift_joint
    command_interfaces:
      - position
      # - velocity
      # - effort
    state_interfaces:
      - position
      - velocity
    open_loop_control: True

head_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - head_1_joint
      - head_2_joint
    command_interfaces:
      - position
      # - velocity
      # - effort
    state_interfaces:
      - position
      - velocity
    open_loop_control: True
