/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Twist.h
  Source: /media/giangnguyen/Storage/Ubuntu2404/Multiverse/Demos/2_UnitreeG1/dds/Twist.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_TWIST_H
#define DDSC_TWIST_H

#include "Vector3.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_dds__Twist_
{
  struct geometry_msgs_msg_dds__Vector3_ linear;
  struct geometry_msgs_msg_dds__Vector3_ angular;
} geometry_msgs_msg_dds__Twist_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__Twist__desc;

#define geometry_msgs_msg_dds__Twist___alloc() \
((geometry_msgs_msg_dds__Twist_*) dds_alloc (sizeof (geometry_msgs_msg_dds__Twist_)));

#define geometry_msgs_msg_dds__Twist__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__Twist__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_TWIST_H */
