/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Vector3.h
  Source: /media/giangnguyen/Storage/Ubuntu2404/Multiverse/Demos/2_UnitreeG1/dds/Vector3.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_VECTOR3_H
#define DDSC_VECTOR3_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_dds__Vector3_
{
  double x;
  double y;
  double z;
} geometry_msgs_msg_dds__Vector3_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__Vector3__desc;

#define geometry_msgs_msg_dds__Vector3___alloc() \
((geometry_msgs_msg_dds__Vector3_*) dds_alloc (sizeof (geometry_msgs_msg_dds__Vector3_)));

#define geometry_msgs_msg_dds__Vector3__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__Vector3__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_VECTOR3_H */
