#!/bin/bash

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 path/to/your/project.muv"
    exit 1
fi

# File name of the MUV file
MUV_FILE=$1

# Check if the file exists
if [ ! -f "$MUV_FILE" ]; then
    echo "Error: File $MUV_FILE not found."
    exit 1
fi

MULTIVERSE_PATH=$(dirname $(dirname $0))

source $MULTIVERSE_PATH/../multiverse_ws/devel/setup.bash

python3 $MULTIVERSE_PATH/modules/multiverse_connectors/multiverse_launch.py "$MUV_FILE"