name: Ubuntu-22.04 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.0

    - name: Run install.sh
      run: |
          chmod +x install.sh
          sudo ./install.sh

    - name: Run build_third_parties.sh
      run: |
          chmod +x build_third_parties.sh
          ./build_third_parties.sh

    - name: Run build_multiverse.sh (only src)
      run: |
          chmod +x build_multiverse.sh
          ./build_multiverse.sh --only-src

    - name: Run build_multiverse.sh (only connectors)
      run: |
          chmod +x build_multiverse.sh
          ./build_multiverse.sh --with-tests --only-modules connectors

    - name: Run build_multiverse_ws2.sh
      run: |
          chmod +x build_multiverse_ws2.sh
          ./build_multiverse_ws2.sh

    - name: Run build_multiverse.sh (only parser)
      run: |
          chmod +x build_multiverse.sh
          ./build_multiverse.sh --only-modules parser

    - name: Test connectors
      run: |
          . /usr/local/bin/virtualenvwrapper.sh
          workon multiverse
          export PYTHONPATH=/usr/lib/python3/dist-packages:/root/.virtualenvs/multiverse/lib/python3.10/site-packages:/home/runner/work/Multiverse/Multiverse/multiverse/build/USD/lib/python:/home/runner/work/Multiverse/Multiverse/multiverse/lib/dist-packages
          python3.10 -m pip install mujoco==3.3.0 mujoco-mjx==3.3.0 "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
          python3.10 -m unittest ./multiverse/modules/multiverse_connectors/src/multiverse_simulators/tests/test_mujoco_compiler.py

    - name: Run build_multiverse.sh
      run: |
          chmod +x build_multiverse.sh
          ./build_multiverse.sh